# fish completion for hed  (SPDX-License-Identifier: MIT)
set -l cmds write show search replace insert delete spell langs edit help
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a write   -d 'Write stdin/-c text to a file (heredoc replacement)'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a show    -d 'Print with highlighting / line numbers'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a search  -d 'Find matches'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a replace -d 'Replace unique text'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a insert  -d 'Insert lines'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a delete  -d 'Delete lines'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a spell   -d 'Spell-check'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a langs   -d 'List languages'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a edit    -d 'Interactive editor'
complete -c hed -s h -l help -d 'Show help'
complete -c hed -l color -x -a 'auto always never'
complete -c hed -s l -l lang -x -a 'python bash fish javascript typescript sql html css json markdown text'
complete -c hed -n '__fish_seen_subcommand_from write' -s c -l content -x -d 'Text to write'
complete -c hed -n '__fish_seen_subcommand_from write' -s d -l dedent -d 'Strip common indentation'
complete -c hed -n '__fish_seen_subcommand_from write' -s a -l append -d 'Append'
complete -c hed -n '__fish_seen_subcommand_from write' -s p -l parents -d 'Create parent dirs'
complete -c hed -n '__fish_seen_subcommand_from write' -s b -l backup -d 'Timestamped backup'
complete -c hed -n '__fish_seen_subcommand_from write' -s m -l mode -x -d 'Octal file mode'
complete -c hed -n '__fish_seen_subcommand_from write' -s n -l no-clobber -d 'Fail if file exists'
complete -c hed -n '__fish_seen_subcommand_from show' -s n -l number -d 'Line numbers'
complete -c hed -n '__fish_seen_subcommand_from show' -s r -l range -x -d 'Line range A:B'
complete -c hed -n '__fish_seen_subcommand_from replace' -s a -l all -d 'Replace all'
complete -c hed -n '__fish_seen_subcommand_from replace' -s n -l dry-run -d 'Show diff only'
complete -c hed -n '__fish_seen_subcommand_from replace' -s E -l regex -d 'Regex mode'
complete -c hed -n '__fish_seen_subcommand_from replace' -l nth -x -d 'Replace Nth match'
complete -c hed -n '__fish_seen_subcommand_from insert' -l after-match -x -d 'Insert after matching line'
complete -c hed -n '__fish_seen_subcommand_from insert' -l at -x -d 'Insert at line N'
complete -c hed -n '__fish_seen_subcommand_from insert' -l end -d 'Append at end'
complete -c hed -n '__fish_seen_subcommand_from delete' -s r -l range -x -d 'Line range'
complete -c hed -n '__fish_seen_subcommand_from spell' -l add -x -d 'Add word to dictionary'
complete -c hed -n '__fish_seen_subcommand_from spell' -l json -d 'JSON output'
