# fish completion for hed  (SPDX-License-Identifier: MIT)
set -l cmds write show search replace insert delete spell langs config log edit help
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a write   -d 'Write stdin/-c text to a file (heredoc replacement)'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a show    -d 'Print with highlighting / line numbers'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a search  -d 'Find matches'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a replace -d 'Replace unique text'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a insert  -d 'Insert lines'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a delete  -d 'Delete lines'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a spell   -d 'Spell-check'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a langs   -d 'List languages'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a config  -d 'View/edit editor config'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a log     -d 'Show editor status log'
complete -c hed -n "not __fish_seen_subcommand_from $cmds" -a edit    -d 'Interactive editor'
complete -c hed -s h -l help -d 'Show help'
complete -c hed -l color -x -a 'auto always never'
complete -c hed -s l -l lang -x -a 'python bash fish javascript typescript sql html css json markdown text'

# write
complete -c hed -n '__fish_seen_subcommand_from write' -s c -l content -x -d 'Text to write'
complete -c hed -n '__fish_seen_subcommand_from write' -s f -l from -r -d 'Read text from FILE'
complete -c hed -n '__fish_seen_subcommand_from write' -s d -l dedent -d 'Strip common indentation'
complete -c hed -n '__fish_seen_subcommand_from write' -s a -l append -d 'Append'
complete -c hed -n '__fish_seen_subcommand_from write' -s p -l parents -d 'Create parent dirs'
complete -c hed -n '__fish_seen_subcommand_from write' -s b -l backup -d 'Timestamped backup'
complete -c hed -n '__fish_seen_subcommand_from write' -s m -l mode -x -d 'Octal file mode'
complete -c hed -n '__fish_seen_subcommand_from write' -s n -l no-clobber -d 'Fail if file exists'
complete -c hed -n '__fish_seen_subcommand_from write' -s t -l strip-tabs -d 'Strip leading tabs'
complete -c hed -n '__fish_seen_subcommand_from write' -s e -l escapes -d 'Interpret \\n \\t etc.'
complete -c hed -n '__fish_seen_subcommand_from write' -l no-eol -d 'No trailing newline'
complete -c hed -n '__fish_seen_subcommand_from write' -s D -l diff -d 'Print unified diff'
complete -c hed -n '__fish_seen_subcommand_from write' -s s -l show -d 'Show written file'
complete -c hed -n '__fish_seen_subcommand_from write' -l spell -d 'Report misspellings'
complete -c hed -n '__fish_seen_subcommand_from write' -s q -l quiet -d 'No summary'

# show
complete -c hed -n '__fish_seen_subcommand_from show' -s n -l number -d 'Line numbers'
complete -c hed -n '__fish_seen_subcommand_from show' -s r -l range -x -d 'Line range A:B'
complete -c hed -n '__fish_seen_subcommand_from show' -s s -l spell -d 'Underline misspellings'

# search
complete -c hed -n '__fish_seen_subcommand_from search' -s E -l regex -d 'Regex mode'
complete -c hed -n '__fish_seen_subcommand_from search' -s i -l ignore-case -d 'Case-insensitive'
complete -c hed -n '__fish_seen_subcommand_from search' -s S -l smart-case -d 'Smart case'
complete -c hed -n '__fish_seen_subcommand_from search' -s w -l word -d 'Whole words'
complete -c hed -n '__fish_seen_subcommand_from search' -s C -l context -x -d 'Context lines'
complete -c hed -n '__fish_seen_subcommand_from search' -s c -l count -d 'Counts only'
complete -c hed -n '__fish_seen_subcommand_from search' -s l -l files -d 'File names only'
complete -c hed -n '__fish_seen_subcommand_from search' -s m -l max -x -d 'Max matches'
complete -c hed -n '__fish_seen_subcommand_from search' -s F -l fixed -d 'Literal (no regex)'
complete -c hed -n '__fish_seen_subcommand_from search' -s n -l line-number -d 'Line numbers'
complete -c hed -n '__fish_seen_subcommand_from search' -l json -d 'JSON output'

# replace
complete -c hed -n '__fish_seen_subcommand_from replace' -l old -x -d 'OLD text'
complete -c hed -n '__fish_seen_subcommand_from replace' -l new -x -d 'NEW text'
complete -c hed -n '__fish_seen_subcommand_from replace' -l old-file -r -d 'Read OLD from file'
complete -c hed -n '__fish_seen_subcommand_from replace' -l new-file -r -d 'Read NEW from file'
complete -c hed -n '__fish_seen_subcommand_from replace' -s a -l all -d 'Replace all'
complete -c hed -n '__fish_seen_subcommand_from replace' -l nth -x -d 'Replace Nth match'
complete -c hed -n '__fish_seen_subcommand_from replace' -l expect -x -d 'Expect N matches'
complete -c hed -n '__fish_seen_subcommand_from replace' -s E -l regex -d 'Regex mode'
complete -c hed -n '__fish_seen_subcommand_from replace' -s i -l ignore-case -d 'Case-insensitive'
complete -c hed -n '__fish_seen_subcommand_from replace' -s r -l range -x -d 'Line range'
complete -c hed -n '__fish_seen_subcommand_from replace' -s e -l escapes -d 'Interpret escapes'
complete -c hed -n '__fish_seen_subcommand_from replace' -s n -l dry-run -d 'Show diff only'
complete -c hed -n '__fish_seen_subcommand_from replace' -s b -l backup -d 'Timestamped backup'
complete -c hed -n '__fish_seen_subcommand_from replace' -s C -l context -x -d 'Diff context'
complete -c hed -n '__fish_seen_subcommand_from replace' -s q -l quiet -d 'No output'
complete -c hed -n '__fish_seen_subcommand_from replace' -l json -d 'JSON output'

# insert
complete -c hed -n '__fish_seen_subcommand_from insert' -s c -l content -x -d 'Text to insert'
complete -c hed -n '__fish_seen_subcommand_from insert' -s f -l from -r -d 'Read from FILE'
complete -c hed -n '__fish_seen_subcommand_from insert' -l at -x -d 'Insert at line N'
complete -c hed -n '__fish_seen_subcommand_from insert' -l before -x -d 'Insert before line N'
complete -c hed -n '__fish_seen_subcommand_from insert' -l after -x -d 'Insert after line N'
complete -c hed -n '__fish_seen_subcommand_from insert' -l start -d 'Insert at top'
complete -c hed -n '__fish_seen_subcommand_from insert' -l end -d 'Insert at bottom'
complete -c hed -n '__fish_seen_subcommand_from insert' -l after-match -x -d 'Insert after matching line'
complete -c hed -n '__fish_seen_subcommand_from insert' -l before-match -x -d 'Insert before matching line'
complete -c hed -n '__fish_seen_subcommand_from insert' -l first -d 'Use first match'
complete -c hed -n '__fish_seen_subcommand_from insert' -s I -l match-indent -d 'Match anchor indent'
complete -c hed -n '__fish_seen_subcommand_from insert' -s d -l dedent -d 'Strip indentation'
complete -c hed -n '__fish_seen_subcommand_from insert' -s t -l strip-tabs -d 'Strip leading tabs'
complete -c hed -n '__fish_seen_subcommand_from insert' -s e -l escapes -d 'Interpret escapes'
complete -c hed -n '__fish_seen_subcommand_from insert' -s n -l dry-run -d 'Show diff only'
complete -c hed -n '__fish_seen_subcommand_from insert' -s b -l backup -d 'Timestamped backup'
complete -c hed -n '__fish_seen_subcommand_from insert' -s C -l context -x -d 'Diff context'
complete -c hed -n '__fish_seen_subcommand_from insert' -s q -l quiet -d 'No output'
complete -c hed -n '__fish_seen_subcommand_from insert' -l json -d 'JSON output'

# delete
complete -c hed -n '__fish_seen_subcommand_from delete' -s r -l range -x -d 'Line range'
complete -c hed -n '__fish_seen_subcommand_from delete' -s L -l lines -x -d 'Line range (alias)'
complete -c hed -n '__fish_seen_subcommand_from delete' -l match -x -d 'Delete matching line'
complete -c hed -n '__fish_seen_subcommand_from delete' -s E -l regex -d 'Regex mode'
complete -c hed -n '__fish_seen_subcommand_from delete' -s a -l all -d 'Delete all matches'
complete -c hed -n '__fish_seen_subcommand_from delete' -s n -l dry-run -d 'Show diff only'
complete -c hed -n '__fish_seen_subcommand_from delete' -s b -l backup -d 'Timestamped backup'
complete -c hed -n '__fish_seen_subcommand_from delete' -s C -l context -x -d 'Diff context'
complete -c hed -n '__fish_seen_subcommand_from delete' -s q -l quiet -d 'No output'
complete -c hed -n '__fish_seen_subcommand_from delete' -l json -d 'JSON output'

# spell
complete -c hed -n '__fish_seen_subcommand_from spell' -s a -l all-text -d 'Check every word'
complete -c hed -n '__fish_seen_subcommand_from spell' -s k -l suggest -x -d 'Suggestions per word'
complete -c hed -n '__fish_seen_subcommand_from spell' -s w -l words -d 'Unique words only'
complete -c hed -n '__fish_seen_subcommand_from spell' -l add -x -d 'Add word to dictionary'
complete -c hed -n '__fish_seen_subcommand_from spell' -s q -l quiet -d 'Exit status only'
complete -c hed -n '__fish_seen_subcommand_from spell' -l json -d 'JSON output'

# config
complete -c hed -n '__fish_seen_subcommand_from config' -a get -d 'Get a setting'
complete -c hed -n '__fish_seen_subcommand_from config' -a set -d 'Set a setting'

# log
complete -c hed -n '__fish_seen_subcommand_from log' -s n -l lines -x -d 'Number of messages'

# edit
complete -c hed -n '__fish_seen_subcommand_from edit' -s T -l tabsize -x -d 'Tab display width'
complete -c hed -n '__fish_seen_subcommand_from edit' -l tabs -d 'Indent with tabs'
complete -c hed -n '__fish_seen_subcommand_from edit' -l spaces -x -d 'Indent with N spaces'
complete -c hed -n '__fish_seen_subcommand_from edit' -l no-spell -d 'Disable spell underline'
complete -c hed -n '__fish_seen_subcommand_from edit' -l no-numbers -d 'Hide line numbers'
complete -c hed -n '__fish_seen_subcommand_from edit' -s R -l readonly -d 'View only'
complete -c hed -n '__fish_seen_subcommand_from edit' -l line -x -d 'Open at line'
complete -c hed -n '__fish_seen_subcommand_from edit' -l log-size -x -d 'Status log size (0=unlimited)'
