#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Generates src/dict_embed.inc from data/en_freq.txt: C definitions of the
# hed_dict_data / hed_dict_end symbols as string literals. This is the portable
# replacement for the GNU-assembler src/dict_embed.S (which used directives the
# macOS assembler rejects), so the same build works on Linux, macOS, and WSL.
#
# Usage: gen_dict.py <input> <output>
import sys


def cstr(data):
    # Keep printable ASCII as-is (escaping " and \), escape everything else as
    # octal so arbitrary bytes survive verbatim.
    out = ['    "']
    for b in data:
        c = chr(b)
        if c == '"':
            out.append('\\"')
        elif c == "\\":
            out.append("\\\\")
        elif 0x20 <= b < 0x7F:
            out.append(c)
        else:
            out.append("\\%03o" % b)
    out.append('"')
    return "".join(out)


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: gen_dict.py <input> <output>\n")
        return 1
    with open(sys.argv[1], "rb") as f:
        data = f.read()

    out = []
    out.append("/* Generated by gen_dict.py from data/en_freq.txt. Do not edit. */\n")
    # extern gives the const symbols external linkage (C file-scope const is
    # internal by default), matching the .global in the original .S.
    out.append("extern const char hed_dict_data[] =\n")
    out.append(cstr(data))
    out.append(";\n")
    # One byte past the data, mirroring the original .S (hed_dict_end: .byte 0).
    out.append("extern const char hed_dict_end[] =\n")
    out.append(cstr(b"\0"))
    out.append(";\n")

    with open(sys.argv[2], "w") as f:
        f.write("".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
